### ISSUE TITLE
Week 0 - Sovereign Tuned

### ISSUE THREAD

**Issue by teowelton** [rh-robotics/19922-CSRC#74]
**Due:** Friday 26th, 2024
**Assigned:** @IsaccBarker
- Sovereign / Roadrunner implementation tuned & tested
- Mark down what needs to be debugged for Week 1 (Week of 1/29/23)

**Comment by olivia-banks** [comment]
Roadrunner tuned close enough that we can test Sovereign.

Week one debug list:
1. Pathing
2. Execution

Component system already tested.

**Comment by teowelton** [comment]
Please Close w/ PR :D @IsaccBarker
